In [1]:
import numpy as np

<img src = "http://community.datacamp.com.s3.amazonaws.com/community/production/ckeditor_assets/pictures/332/content_arrays-axes.png">

# NumPy Array Syntax
The function array takes two arguments: the list to be converted into the array and the type of each member of the list. 

In [2]:
#List to be converted
lst = [1,2,3,4,5,6,7,8,9]

arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Array elements are accessed, sliced, and manipulated just like lists.

In [3]:
#Index from the 2nd index on
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [4]:
#manipulate item at index 0
arr[0] = 10
arr

array([10,  2,  3,  4,  5,  6,  7,  8,  9])

# Python List VS NumPy Array

"Arrays and lists are both used in Python to store data, but they don't serve exactly the same purposes. They both can be used to store any data type (real numbers, strings, etc), and they both can be indexed and iterated through, but the similarities between the two don't go much further. The main difference between a list and an array is the functions that you can perform to them. For example, you can divide an array by 3, and each number in the array will be divided by 3 and the result will be printed if you request it. If you try to divide a list by 3, Python will tell you that it can't be done, and an error will be thrown."


In [5]:
lst = [3,6,9,12,15,18,12]
lst/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [6]:
arr = np.array([3,6,9,12,15,18,12])
arr1 = arr * 4
print(arr1)

[12 24 36 48 60 72 48]


In [7]:
display(arr1)

array([12, 24, 36, 48, 60, 72, 48])

Arrays can be multidimensional. Unlike lists, different axes are accessed using commas inside bracket notation. Here is an example with a two-dimensional array (e.g., a matrix)

In [8]:
lst1 = [1,2,3,4,5]
lst2 = [5,6,7,8,9]
arr = np.array([lst2,lst1])
arr

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [9]:
(arr/3)

array([[1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ],
       [0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667]])

In [10]:
lst_lst = [lst1,lst2]
lst_lst

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

In [11]:
lst_lst/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# Indexing Arrays VS Lists

In [12]:
arr

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [13]:
arr[0][1]

6

In [14]:
lst_lst

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

In [15]:
lst_lst[0,1]

TypeError: list indices must be integers or slices, not tuple

In [16]:
lst_lst[0][1]

2

In [17]:
arr[-1]

array([1, 2, 3, 4, 5])

In [18]:
lst_lst[-1]

[5, 6, 7, 8, 9]

In [19]:
arr

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

<h3> How to index a multidemsional array? </h3><br>
The individual elements of arrays can be accessed in the same way as for lists.

<img src = "http://www.scipy-lectures.org/_images/numpy_indexing.png" height = 60% width = 60%>

In [20]:
list_2d = [[0,1,2,3,4,5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]]

In [21]:
array_2d = np.array(list_2d)
print(array_2d)
array_2d.shape

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


(6, 6)

In [22]:
print(array_2d[0,3:5])

[3 4]


In [23]:
print(array_2d[4:,4:])

[[44 45]
 [54 55]]


In [24]:
print(array_2d[:,2])

[ 2 12 22 32 42 52]


In [25]:
print(array_2d[2:5:2,3::2]) # step by 2

[[23 25]
 [43 45]]


In [26]:
# adding new column to numpy array

In [27]:
calc = array_2d[:,5] * 1.05
# new_column = np.array(calc)
print(calc)

[ 5.25 15.75 26.25 36.75 47.25 57.75]


In [28]:
new_array_2d = np.column_stack((array_2d,calc))
print(new_array_2d)

[[ 0.    1.    2.    3.    4.    5.    5.25]
 [10.   11.   12.   13.   14.   15.   15.75]
 [20.   21.   22.   23.   24.   25.   26.25]
 [30.   31.   32.   33.   34.   35.   36.75]
 [40.   41.   42.   43.   44.   45.   47.25]
 [50.   51.   52.   53.   54.   55.   57.75]]


# Changing Array to different DataType

In [29]:
mylist = arr.tolist()
print(mylist)

[[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]


In [30]:
type(arr)

numpy.ndarray

In [31]:
arr = np.array(arr)
arr

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [32]:
type(arr)

numpy.ndarray

In [33]:
arr.shape

(2, 5)

# Change Array Shape

Transposed versions of arrays can also be generated, which will create a new array with the final two axes switched:

In [34]:
arr

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [35]:
arr.shape

(2, 5)

In [36]:
arr.transpose()

array([[5, 1],
       [6, 2],
       [7, 3],
       [8, 4],
       [9, 5]])

In [37]:
arr.transpose().shape

(5, 2)

Make multidimensional array into one-dimensional array

In [38]:
arr.shape

(2, 5)

In [39]:
arr.flatten()

array([5, 6, 7, 8, 9, 1, 2, 3, 4, 5])

In [40]:
arr.flatten().shape

(10,)

# Create New Array (Specific)

Numpy also provides many functions to create arrays.

Creates an array of all zeros with a specified shape.

In [41]:
#1-Dimensional
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
#2-Dimensional
np.zeros((2,2), int)

array([[0, 0],
       [0, 0]])

Creates an array of all ones with a specified shape.

In [43]:
#1-Dimensional
np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
#2-Dimensional
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Creates a constant array (specified number) with a specified shape.

In [45]:
#1-Dimensional
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [46]:
#2-Dimensional
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

Created an array of a specified shape with random values.

In [47]:
#1-Dimensional
np.random.random(10)

array([0.72630021, 0.86388985, 0.40593828, 0.49350439, 0.22933878,
       0.03875007, 0.97197167, 0.15111938, 0.27601477, 0.72103725])

In [48]:
#2-Dimensional
np.random.random((2,2))

array([[0.05381017, 0.89898305],
       [0.02180223, 0.29589705]])

Create an array of a specified length with evenly spaced values.

In [49]:
#1-Dimensional
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an array with a specified "start", "stop", and number of values, evenly spaced.

In [50]:
#1-Dimensional
np.linspace(1, 10, num = 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

Creates a 2x2 identity matrix (array).

An identity matrix is a square matrix having 1s on the main diagonal, and 0s everywhere else. These are called identity matrices because, when you multiply them with a compatible matrix , you get back the same matrix.
http://www.sparknotes.com/math/algebra2/matrices/section3.rhtml

In [51]:
#2-Dimensional
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

OR

In [52]:
#2-Dimensional
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Math Functions using NumPy

"As such, it probably won’t surprise you that you can just use +, -, *, / or % to add, subtract, multiply, divide or calculate the remainder of two (or more) arrays. However, a big part of why NumPy is so handy, is because it also has functions to do this. The equivalent functions of the operations that you have seen just now are, respectively, np.add(), np.subtract(), np.multiply(), np.divide() and np.remainder()."

https://www.datacamp.com/community/tutorials/python-numpy-tutorial

In [53]:
arr = np.ones((10,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
np.add(arr,2)

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [55]:
#OR
arr + 2

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [56]:
np.multiply(arr,3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [57]:
#OR
arr*2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [58]:
np.subtract(arr,1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
#OR
arr -1 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.divide(arr,2)

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [61]:
#OR
arr/2

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [62]:
np.remainder(arr,1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
#OR
arr % 1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
arr.sum()

100.0

In [65]:
arr.min()

1.0

In [66]:
arr.max()

1.0

In [67]:
arr.mean()

1.0

# Numpy with Bay Area housing data set

In [68]:
def read_file_housing(filename):
    file_open = open(filename,"r")
    fixed_file = open("fixed-housing-data.csv","w")
    line_count = 0
    for line in iter(file_open):
        line_count += 1
        if "HomeID" in line:
            continue
        line_no_newline = line.rstrip()
        line1 = line_no_newline.replace("84085","94085") #Ex9
        line2 = line1.replace("84087","94087") #Ex9
        line3 = line2.replace("85014","95014") #Ex9
        line4 = line3.replace("85051","95051") #Ex9
        line5 = line4.replace("l","1") #Ex11 -- Car_Garage
        line_split = line5.split(",")
        if (int(line_split[5]) < 100): #Ex10 -- School_API
            line_split[5] = int(line_split[5]) * 10
        else:
            line_split[5] = int(line_split[5])
        line_split = [str(x) for x in line_split]
        myString = ",".join(line_split) + "\n"
        fixed_file.write(myString)
    file_open.close()
    fixed_file.close()
    return

In [71]:
read_file_housing("bayarea_home_prices.csv")

In [72]:
"""
0 = HomeID
1 = HomeAge
2 = HomeSqft
3 = LotSize
4 = BedRooms
5 = HighSchoolAPI
6 = ProxFwy
7 = CarGarage
8 = ZipCode
9 = HomePriceK
"""

'\n0 = HomeID\n1 = HomeAge\n2 = HomeSqft\n3 = LotSize\n4 = BedRooms\n5 = HighSchoolAPI\n6 = ProxFwy\n7 = CarGarage\n8 = ZipCode\n9 = HomePriceK\n'

In [73]:
housing = np.loadtxt("fixed-housing-data.csv",
                          dtype=int,
                          delimiter=",")

In [74]:
print(housing[0:2])

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]]


In [75]:
print(housing.shape)

(100, 10)


In [76]:
# home prices
print(housing[:,9])

[ 894  861  831  809  890  867  843  820  874  885  903  912  933  865
  918  950  882  896  942  859  904  912  916  972  908  934  914  949
  919  953  991 1049 1042  994 1030 1019 1044 1038 1024  976 1115 1128
 1071 1059 1000 1185 1015 1114 1138 1068 1068 1097 1074 1114 1075 1130
 1116 1103 1080 1150 1177 1149 1163 1132 1138 1199 1179 1173 1128 1165
 1233 1180 1240 1242 1184 1173 1194 1181 1190 1182 1221 1288 1275 1300
 1272 1294 1219 1282 1256 1205 1252 1294 1269 1335 1267 1307 1336 1284
 1269 1250]


In [77]:
inflation = 0.1
print(housing[:,9] *(1+inflation))

[ 983.4  947.1  914.1  889.9  979.   953.7  927.3  902.   961.4  973.5
  993.3 1003.2 1026.3  951.5 1009.8 1045.   970.2  985.6 1036.2  944.9
  994.4 1003.2 1007.6 1069.2  998.8 1027.4 1005.4 1043.9 1010.9 1048.3
 1090.1 1153.9 1146.2 1093.4 1133.  1120.9 1148.4 1141.8 1126.4 1073.6
 1226.5 1240.8 1178.1 1164.9 1100.  1303.5 1116.5 1225.4 1251.8 1174.8
 1174.8 1206.7 1181.4 1225.4 1182.5 1243.  1227.6 1213.3 1188.  1265.
 1294.7 1263.9 1279.3 1245.2 1251.8 1318.9 1296.9 1290.3 1240.8 1281.5
 1356.3 1298.  1364.  1366.2 1302.4 1290.3 1313.4 1299.1 1309.  1300.2
 1343.1 1416.8 1402.5 1430.  1399.2 1423.4 1340.9 1410.2 1381.6 1325.5
 1377.2 1423.4 1395.9 1468.5 1393.7 1437.7 1469.6 1412.4 1395.9 1375. ]


In [78]:
print(housing.sum(axis=0)) # sum by columns

[   5050    1720  161528  784050     271   90443     310     152 9455925
  108099]


In [79]:
print(housing.sum(axis=1)) # sum by rows

[103724 103574 103240 103224 103896 103638 104044 103869 103609 104170
 104094 103592 103978 104376 104062 105595 104218 104335 104940 104012
 104075 104583 104684 105583 104958 104446 104876 105593 104503 106006
 105990 106058 106256 105929 106298 105629 106320 106196 106023 106261
 105369 105445 106369 105987 105936 105549 106606 105320 105358 106782
 106365 106479 106225 105461 106713 105795 106138 105594 106827 105847
 105796 106180 105869 105800 106169 107018 106669 106315 106430 106551
 107465 106524 107181 107608 106533 107139 107961 106805 106554 106595
 107843 107864 108077 107983 108182 108227 107735 107879 108478 108106
 107902 108487 107956 108654 108172 108678 108406 108111 108617 108407]


In [80]:
homes_94085 = (housing[:,8] == 94085)

In [81]:
print(homes_94085)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True False  True  True  True  True False
  True  True  True False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]


In [82]:
data_94085 = housing[homes_94085,][:,:]
print(data_94085)

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    3    14  1344  6089     2   865     4     3 94085   831]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [    5    24  1866  6141     3   877     4     1 94085   890]
 [    6    18  1589  6148     2   920     3     0 94085   867]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [    8    19  1839  6186     3   905     4     0 94085   820]
 [    9    17  1501  6233     2   884     3     1 94085   874]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   11    12  1798  6346     3   931     3     2 94085   903]
 [   12    22  1221  6430     3   904     2     1 94085   912]
 [   13    15  1541  6514     2   872     2     1 94085   933]
 [   14    25  1974  6547     2   857     4     3 94085   865]
 [   15    10  1510  6633     2   884     3     2 94085   918]
 [   17    23  1464  6773     3   965     4     2 94085

In [83]:
sum_price_94085 = data_94085[:,9].sum()
print(sum_price_94085)

22149


In [84]:
print(len(data_94085))

25


In [85]:
print(data_94085.shape[0])

25


In [86]:
print(data_94085.shape[1])

10


In [87]:
average_94085 = sum_price_94085/25
print(average_94085)

885.96


In [88]:
h1 = housing[housing[:,5].argsort()] # by school_api ascending
print(h1)

[[   65    14  1617  8394     2   850     2     0 94087  1138]
 [   73    25  1302  8668     3   850     4     2 95014  1240]
 [   23    15  1828  6956     3   851     4     3 94085   916]
 [   20    13  1358  6819     2   851     3     2 94085   859]
 [   79    17  1373  8953     2   851     2     0 94087  1190]
 [   77    17  1881  8921     3   852     2     0 95014  1194]
 [   19    10  1246  6810     2   853     4     3 95051   942]
 [   32    18  1866  7181     2   854     2     3 95051  1049]
 [   95    13  1582  9339     3   856     3     0 95014  1267]
 [   26    12  1500  7025     2   856     4     2 94085   934]
 [   99    19  1880  9470     3   857     3     3 95014  1269]
 [   53    23  1289  7873     2   857     3     0 95051  1074]
 [   67    24  1947  8502     2   857     4     0 94087  1179]
 [  100    11  1691  9476     4   857     4     0 95014  1250]
 [   14    25  1974  6547     2   857     4     3 94085   865]
 [   44    11  1415  7541     3   859     4     0 95051

In [89]:
h2 = housing[housing[:,5].argsort()[::-1]] # by school_api descending
print(h2)

[[   38    22  1724  7339     3   975     3     3 95051  1038]
 [   35    12  1943  7249     2   974     2     0 95051  1030]
 [   27    13  1836  7027     2   966     3     3 94085   914]
 [   17    23  1464  6773     3   965     4     2 94085   882]
 [   69    21  1575  8579     2   962     4     3 94087  1128]
 [   37    13  1874  7333     3   960     3     2 95051  1044]
 [   45    15  1249  7609     3   960     2     2 95051  1000]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [   33    11  1953  7199     3   959     3     2 95051  1042]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [   76    12  1947  8882     3   954     3     2 94087  1173]
 [   59    22  1559  8096     2   953     2     3 95051  1080]
 [   57    11  1927  7983     3   950     3     1 94087  1116]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   50    19  1836  7803     3   949     3     0 95051